### ISSUE TITLE
Incompatible with mohist-1.18.2

### ISSUE THREAD

**Issue by SeanChengN** [spoorn/SpoornArmorAttributes#7]
Crash when starting server, test with the following environment:
[mohist-1.18.2-90-server.jar](https://github.com/MohistMC/Mohist/tree/1.18.2)
cloth-config-6.2.62-forge.jar
spoornarmorattributes-1.0.4-1.18-forge.jar

However, spoornweaponattributes-3.4.7-1.18-forge.jar works well.
log: https://pastebin.com/VpYpccw8

**Comment by spoorn** [comment]
Could you try [spoornarmorattributes-1.0.5-1.18-forge](https://www.curseforge.com/minecraft/mc-mods/spoorn-armorattributes/files/3944541)

**Comment by SeanChengN** [comment]
> Could you try [spoornarmorattributes-1.0.5-1.18-forge](https://www.curseforge.com/minecraft/mc-mods/spoorn-armorattributes/files/3944541)

Crash
https://pastebin.com/sG2z8CPp
https://pastebin.com/hC1itxmr

**Comment by spoorn** [comment]
Looks like the mixin injection failed.  Not sure if mohist is changing the forge server source code or what, but it injects fine with the regular Forge server.  I don't quite have the bandwidth to dig into this at the moment and only have the time to make sure the official Forge is supported.  Sorry.  I do see mohist says 1.18.2 is in Testing stage, so maybe that's why?  If I have time later or more people have issues with this I can look into this further at a later time
